
#ckbPath: #replace here with the full path where ckb binary located, e.g. /Users/Dev/ckb
#nodePath: #replace here with ckb node's full path, e.g. /Users/Dev/ckb/test
#chromedriverPath: ./chromedriver-v7.1.11-mas-x64/chromedriver
